# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ netcat_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - netcat
    - netcat-install
    - netcat-install-dependencies

- name: update alternatives
  community.general.alternatives:
    name: nc
    path: /bin/nc.traditional
  tags:
    - configuration
    - netcat
    - netcat-update-alternatives
